DEFAULT_MODEL: str

def init_index(repo: str) -> None: ...
def walk_repo(repo: str, max_files: int | None) -> str: ...
def parse_source(language: str, path_suffix: str, source: bytes) -> str: ...
def run_scan(
    repo: str,
    max_files: int | None,
    budget_seconds: float | None,
    with_git: bool,
    with_embed: bool,
    model_name: str,
) -> str: ...
def choose_call_targets(
    callee: str,
    targets: list[tuple[int, int]],
    src_file_id: int,
    langs: dict[int, str],
) -> list[tuple[int, int]]: ...
def resolve_and_store_edges(repo: str) -> None: ...
def file_graph(repo: str) -> str: ...
def pagerank(
    nodes: list[int],
    edges: list[tuple[int, int]],
    personalize: dict[int, float] | None,
    damping: float,
    rounds: int,
) -> dict[int, float]: ...
def dead_symbols(repo: str) -> str: ...
def dead_files(repo: str) -> str: ...
def dead_report(repo: str) -> str: ...
def slice_symbol(repo: str, query: str, depth: int) -> str: ...
def apply_issues(repo: str) -> str: ...
def list_issues(repo: str, limit: int) -> str: ...
def tokenize_name(name: str) -> list[str]: ...
def analyze_names(repo: str) -> str: ...
def find_clones(repo: str) -> str: ...
def find_embed_clones(repo: str) -> str: ...
def label_clusters(repo: str) -> str: ...
def embed_symbols(repo: str, model_name: str, only_missing: bool) -> None: ...
def mismatch_flags(repo: str) -> str: ...
def similar_to(repo: str, query: str) -> str: ...
def export_label_csv(repo: str, dest: str) -> int: ...
def use_stub(model_name: str) -> bool: ...
def compute_rank(repo: str) -> str: ...
def reading_order(repo: str, limit: int) -> str: ...
def analyze_history(repo: str) -> str: ...
def history_report(repo: str) -> str: ...
def write_heatmap(repo: str, dest: str, slice_files: list[str] | None) -> str: ...
def write_report_dir(repo: str, extra_json: str) -> str: ...
def refresh_report(repo: str) -> str: ...
def review_pack(repo: str, dest: str, slice_query: str | None) -> str: ...
def ingest_profile(repo: str, profile_path: str) -> str: ...
def launch_or_attach(
    repo: str,
    lang: str,
    pid: int | None,
    command: list[str],
    dest: str,
    duration: int,
) -> str: ...
def package_map(repo: str) -> str: ...
def inventory(repo: str) -> str: ...
def tag_effects(body: str) -> list[str]: ...
def apply_effects(repo: str) -> None: ...
def tag_risks(name: str, body: str, signature: str) -> list[str]: ...
def apply_risks(repo: str) -> str: ...
def cost_hint(body: str) -> int: ...
def apply_cost_hints(repo: str) -> None: ...
def is_hollow(body: str, docstring: str) -> str: ...
def hollow_symbols(repo: str) -> str: ...
def apply_hollow(repo: str) -> str: ...
def fingerprint_symbol(
    name: str,
    effects: list[str],
    fan_in: int,
    fan_out: int,
    cyclomatic: int,
    cognitive: int,
    callees: list[str],
) -> str: ...
def fingerprint_overlap(a: str, b: str) -> float: ...
def apply_fingerprints(repo: str) -> None: ...
